// Copyright 2017-2026 the LinuxBoot Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package cbnt

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"io"

	"github.com/linuxboot/fiano/pkg/intel/metadata/common/pretty"
)

var chipsetACModuleInformationSignature = []byte{
	0xAA, 0x3A, 0xC0, 0x7F, 0xA7, 0x46, 0xDB, 0x18,
	0x2E, 0xAC, 0x69, 0x8F, 0x8D, 0x41, 0x7F, 0x5A,
}

// TODO: futher cleanup to get rid of funcs that were generated by manifestcodegen, but do not
// do anything useful on this structure (from brief look, getter for offset is fairly useless).

// NewChipsetACModuleInformation returns a new instance of ChipsetACModuleInformation with
// all default values set.
func NewChipsetACModuleInformation() *ChipsetACModuleInformation {
	s := &ChipsetACModuleInformation{}
	s.Rehash()
	return s
}

// ParseChipsetACModuleInformation parses Chipset AC Module Information Table according to the version
func ParseChipsetACModuleInformation(r io.Reader) (int64, ChipsetACModuleInformationV5, error) {
	var result ChipsetACModuleInformationV5
	total, err := result.Base.ReadFrom(r)
	if !bytes.Equal(result.Base.UUID[:], chipsetACModuleInformationSignature) {
		return 0, ChipsetACModuleInformationV5{}, fmt.Errorf(
			"incorrect UUID [%x], expected: [%x]", result.Base.UUID, chipsetACModuleInformationSignature)
	}
	if err != nil {
		return total, result, err
	}
	if result.Base.Version < 5 {
		return total, result, nil
	}
	err = binary.Read(r, binary.LittleEndian, &result.TPMInfoList)
	total += int64(binary.Size(result.TPMInfoList))
	return total, result, err
}

// ReadFrom reads the ChipsetACModuleInformation from 'r' in format defined in the document #575623.
func (s *ChipsetACModuleInformation) ReadFrom(r io.Reader) (int64, error) {
	totalN, err := s.Common.ReadFrom(r, s)
	if err != nil {
		return 0, err
	}

	return totalN, nil
}

// RehashRecursive calls Rehash (see below) recursively.
func (s *ChipsetACModuleInformation) RehashRecursive() {
	s.Rehash()
}

// Rehash sets values which are calculated automatically depending on the rest
// data. It is usually about the total size field of an element.
func (s *ChipsetACModuleInformation) Rehash() {
}

// WriteTo writes the ChipsetACModuleInformation into 'w' in format defined in
// the document #575623.
func (s *ChipsetACModuleInformation) WriteTo(w io.Writer) (int64, error) {
	totalN := int64(0)
	s.Rehash()

	// UUID (ManifestFieldType: arrayStatic)
	{
		n, err := 16, binary.Write(w, binary.LittleEndian, s.UUID[:])
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'UUID': %w", err)
		}
		totalN += int64(n)
	}

	// ChipsetACMType (ManifestFieldType: endValue)
	{
		n, err := 1, binary.Write(w, binary.LittleEndian, &s.ChipsetACMType)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'ChipsetACMType': %w", err)
		}
		totalN += int64(n)
	}

	// Version (ManifestFieldType: endValue)
	{
		n, err := 1, binary.Write(w, binary.LittleEndian, &s.Version)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'Version': %w", err)
		}
		totalN += int64(n)
	}

	// Length (ManifestFieldType: endValue)
	{
		n, err := 2, binary.Write(w, binary.LittleEndian, &s.Length)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'Length': %w", err)
		}
		totalN += int64(n)
	}

	// ChipsetIDList (ManifestFieldType: endValue)
	{
		n, err := 4, binary.Write(w, binary.LittleEndian, &s.ChipsetIDList)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'ChipsetIDList': %w", err)
		}
		totalN += int64(n)
	}

	// OsSinitDataVer (ManifestFieldType: endValue)
	{
		n, err := 4, binary.Write(w, binary.LittleEndian, &s.OsSinitDataVer)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'OsSinitDataVer': %w", err)
		}
		totalN += int64(n)
	}

	// MinMleHeaderVer (ManifestFieldType: endValue)
	{
		n, err := 4, binary.Write(w, binary.LittleEndian, &s.MinMleHeaderVer)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'MinMleHeaderVer': %w", err)
		}
		totalN += int64(n)
	}

	// Capabilities (ManifestFieldType: endValue)
	{
		n, err := 4, binary.Write(w, binary.LittleEndian, &s.Capabilities)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'Capabilities': %w", err)
		}
		totalN += int64(n)
	}

	// AcmVersion (ManifestFieldType: endValue)
	{
		n, err := 1, binary.Write(w, binary.LittleEndian, &s.AcmVersion)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'AcmVersion': %w", err)
		}
		totalN += int64(n)
	}

	// AcmRevision (ManifestFieldType: arrayStatic)
	{
		n, err := 3, binary.Write(w, binary.LittleEndian, s.AcmRevision[:])
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'AcmRevision': %w", err)
		}
		totalN += int64(n)
	}

	// ProcessorIDList (ManifestFieldType: endValue)
	{
		n, err := 4, binary.Write(w, binary.LittleEndian, &s.ProcessorIDList)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'ProcessorIDList': %w", err)
		}
		totalN += int64(n)
	}

	return totalN, nil
}

func (s *ChipsetACModuleInformation) Layout() []LayoutField {
	return []LayoutField{
		{
			ID:    0,
			Name:  "UUID",
			Size:  func() uint64 { return 16 },
			Value: func() any { return &s.UUID },
			Type:  ManifestFieldArrayStatic,
		},
		{
			ID:    1,
			Name:  "Chipset ACM Type",
			Size:  func() uint64 { return 1 },
			Value: func() any { return &s.ChipsetACMType },
			Type:  ManifestFieldEndValue,
		},
		{
			ID:    2,
			Name:  "Version",
			Size:  func() uint64 { return 1 },
			Value: func() any { return &s.Version },
			Type:  ManifestFieldEndValue,
		},
		{
			ID:    3,
			Name:  "Length",
			Size:  func() uint64 { return 2 },
			Value: func() any { return &s.Length },
			Type:  ManifestFieldEndValue,
		},
		{
			ID:    4,
			Name:  "Chipset ID List",
			Size:  func() uint64 { return 4 },
			Value: func() any { return &s.ChipsetIDList },
			Type:  ManifestFieldEndValue,
		},
		{
			ID:    5,
			Name:  "Os Sinit Data Ver",
			Size:  func() uint64 { return 4 },
			Value: func() any { return &s.OsSinitDataVer },
			Type:  ManifestFieldEndValue,
		},
		{
			ID:    6,
			Name:  "Min Mle Header Ver",
			Size:  func() uint64 { return 4 },
			Value: func() any { return &s.MinMleHeaderVer },
			Type:  ManifestFieldEndValue,
		},
		{
			ID:    7,
			Name:  "Capabilities",
			Size:  func() uint64 { return 4 },
			Value: func() any { return &s.Capabilities },
			Type:  ManifestFieldEndValue,
		},
		{
			ID:    8,
			Name:  "Acm Version",
			Size:  func() uint64 { return 1 },
			Value: func() any { return &s.AcmVersion },
			Type:  ManifestFieldEndValue,
		},
		{
			ID:    9,
			Name:  "Acm Revision",
			Size:  func() uint64 { return 3 },
			Value: func() any { return &s.AcmRevision },
			Type:  ManifestFieldArrayStatic,
		},
		{
			ID:    10,
			Name:  "Processor ID List",
			Size:  func() uint64 { return 4 },
			Value: func() any { return &s.ProcessorIDList },
			Type:  ManifestFieldEndValue,
		},
	}
}

func (s *ChipsetACModuleInformation) SizeOf(id int) (uint64, error) {
	ret, err := s.Common.SizeOf(s, id)
	if err != nil {
		return ret, fmt.Errorf("HashList: %v", err)
	}

	return ret, nil
}

func (s *ChipsetACModuleInformation) OffsetOf(id int) (uint64, error) {
	ret, err := s.Common.OffsetOf(s, id)
	if err != nil {
		return ret, fmt.Errorf("HashList: %v", err)
	}

	return ret, nil
}

func (s *ChipsetACModuleInformation) TotalSize() uint64 {
	if s == nil {
		return 0
	}

	return s.Common.TotalSize(s)
}

// PrettyString returns the content of the structure in an easy-to-read format.
func (s *ChipsetACModuleInformation) PrettyString(depth uint, withHeader bool, opts ...pretty.Option) string {
	return Common{}.PrettyString(depth, withHeader, s, "Chipset AC Module Information", opts...)
}

// NewChipsetACModuleInformationV5 returns a new instance of ChipsetACModuleInformationV5 with
// all default values set.
func NewChipsetACModuleInformationV5() *ChipsetACModuleInformationV5 {
	s := &ChipsetACModuleInformationV5{}
	// Recursively initializing a child structure:
	s.Base = *NewChipsetACModuleInformation()
	s.Rehash()
	return s
}

// ReadFrom reads the ChipsetACModuleInformationV5 from 'r' in format defined in the document #575623.
func (s *ChipsetACModuleInformationV5) ReadFrom(r io.Reader) (int64, error) {
	totalN, err := s.Common.ReadFrom(r, s)
	if err != nil {
		return 0, err
	}

	return totalN, nil
}

// RehashRecursive calls Rehash (see below) recursively.
func (s *ChipsetACModuleInformationV5) RehashRecursive() {
	s.Base.Rehash()
	s.Rehash()
}

// Rehash sets values which are calculated automatically depending on the rest
// data. It is usually about the total size field of an element.
func (s *ChipsetACModuleInformationV5) Rehash() {
}

// WriteTo writes the ChipsetACModuleInformationV5 into 'w' in format defined in
// the document #575623.
func (s *ChipsetACModuleInformationV5) WriteTo(w io.Writer) (int64, error) {
	totalN := int64(0)
	s.Rehash()

	// Base (ManifestFieldType: subStruct)
	{
		n, err := s.Base.WriteTo(w)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'Base': %w", err)
		}
		totalN += int64(n)
	}

	// TPMInfoList (ManifestFieldType: endValue)
	{
		n, err := 4, binary.Write(w, binary.LittleEndian, &s.TPMInfoList)
		if err != nil {
			return totalN, fmt.Errorf("unable to write field 'TPMInfoList': %w", err)
		}
		totalN += int64(n)
	}

	return totalN, nil
}

func (s *ChipsetACModuleInformationV5) Layout() []LayoutField {
	return []LayoutField{
		{
			ID:    0,
			Name:  "Base",
			Size:  func() uint64 { return s.Base.Common.TotalSize(&s.Base) },
			Value: func() any { return &s.Base },
			Type:  ManifestFieldSubStruct,
		},
		{
			ID:    1,
			Name:  "TPM Info List",
			Size:  func() uint64 { return 4 },
			Value: func() any { return &s.TPMInfoList },
			Type:  ManifestFieldSubStruct,
		},
	}
}

func (s *ChipsetACModuleInformationV5) SizeOf(id int) (uint64, error) {
	ret, err := s.Common.SizeOf(s, id)
	if err != nil {
		return ret, fmt.Errorf("HashList: %v", err)
	}

	return ret, nil
}

func (s *ChipsetACModuleInformationV5) OffsetOf(id int) (uint64, error) {
	ret, err := s.Common.OffsetOf(s, id)
	if err != nil {
		return ret, fmt.Errorf("HashList: %v", err)
	}

	return ret, nil
}

func (s *ChipsetACModuleInformationV5) TotalSize() uint64 {
	if s == nil {
		return 0
	}

	return s.Common.TotalSize(s)
}

// PrettyString returns the content of the structure in an easy-to-read format.
func (s *ChipsetACModuleInformationV5) PrettyString(depth uint, withHeader bool, opts ...pretty.Option) string {
	return Common{}.PrettyString(depth, withHeader, s, "Chipset AC Module Information V 5", opts...)
}
